Shooter:
  measure: reward
  thresholds: [0.5, 0.5]
  min_lesson_length: 100
  signal_smoothing: true
  parameters:
    amountZombies: [3, 6, 6]
    zombieSpeed: [1, 1.5, 2]
    shootingFrequenzy: [15, 40, 125]

